#!/bin/bash
pushd src
VCS_REF=$(git rev-parse HEAD)
GO_VERSION=$(cat version/version.go | awk 'match($0, /[0-9].[0-9].[0-9]/) {print substr( $0, RSTART, RLENGTH )}')
popd
echo ${IMAGE_NAME}
docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${VCS_REF}
docker push ${DOCKER_REPO}:${VCS_REF}
docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${GO_VERSION}
docker push ${DOCKER_REPO}:${GO_VERSION}
